# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 01:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_name', models.CharField(default='', max_length=100, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator("^[A-Za-z0-9-_ \\'!]+$", "Permitted characters: alphanumeric, space, -, _, ', !.")])),
                ('creator', models.CharField(default='', max_length=80, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Permitted characters: alphabet, space.')])),
                ('username', models.CharField(default='', max_length=100)),
                ('uri', models.CharField(default='', max_length=140)),
                ('url', models.CharField(default='', max_length=140, unique=True)),
                ('created_at', models.DateTimeField(default='1995-07-12T13:20:30-08:00')),
                ('host', models.CharField(default='', max_length=100)),
                ('host_display', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_title', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('artist', models.CharField(default='', max_length=100)),
                ('score', models.IntegerField(default=1)),
                ('uri', models.CharField(default='', max_length=140)),
                ('current', models.BooleanField(default=False)),
                ('party', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='upnext.Party')),
            ],
        ),
    ]
