# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 18:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_name', models.CharField(default='', max_length=100, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-_]+$', 'Permitted characters: alphanumeric, dash, underscore.')])),
                ('user_nickname', models.CharField(default='', max_length=80, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', 'Permitted characters: alphabet.')])),
                ('username', models.CharField(default='', max_length=100)),
                ('uri', models.CharField(default='', max_length=140)),
                ('created_at', models.DateTimeField(default='1995-07-12T13:20:30-08:00')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_title', models.CharField(default='', max_length=100)),
                ('artist', models.CharField(default='', max_length=100)),
                ('score', models.IntegerField(default=1)),
                ('uri', models.CharField(default='', max_length=140)),
                ('party', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='upnext.Party')),
            ],
        ),
    ]
