# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.CharField(default='Unknown Artist', max_length=200),
        ),
    ]
