# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 21:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 23, 21, 25, 10, 870629, tzinfo=utc)),
        ),
    ]
