# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='voters',
            field=models.ManyToManyField(to='upnext.Voter'),
        ),
    ]
