# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='id',
        ),
        migrations.AlterField(
            model_name='track',
            name='track_title',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
