# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 22:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='url',
            field=models.CharField(default='', max_length=140, unique=True, validators=[django.core.validators.RegexValidator('^[A-za-z0-9-]+$', 'Permitted characters: alphanumeric, dashes.')]),
        ),
    ]
