# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0002_auto_20160726_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='host',
            field=models.CharField(default='', max_length=100),
        ),
    ]
