# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 23:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0002_auto_20160728_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='party_name',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator("^[A-Za-z0-9-_ \\'!]+$", "Permitted party name characters: alphanumeric, space, -, _, ', !.")]),
        ),
        migrations.AlterField(
            model_name='party',
            name='url',
            field=models.CharField(default='', max_length=140, unique=True, validators=[django.core.validators.RegexValidator('^[A-za-z0-9-]+$', 'Permitted URL characters: alphanumeric, dashes.')]),
        ),
        migrations.AlterField(
            model_name='party',
            name='user_nickname',
            field=models.CharField(default='', max_length=80, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Permitted user nickname characters: alphabet, space.')]),
        ),
    ]
