# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 03:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0002_auto_20160723_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 25, 3, 11, 1, 866770, tzinfo=utc)),
        ),
    ]
