# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 17:37
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0003_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 20, 17, 37, 7, 373413, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='party',
            name='user_nickname',
            field=models.CharField(default='No Nickname Provided', max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', 'This field can have characters: alphabet.')]),
        ),
        migrations.AddField(
            model_name='party',
            name='username',
            field=models.CharField(default='No Username', max_length=200),
        ),
        migrations.AddField(
            model_name='track',
            name='party',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='upnext.Party'),
        ),
        migrations.AddField(
            model_name='track',
            name='uri',
            field=models.CharField(default='spotify:track:7dpH9X1L0EeDCJr0jr1ZX0', max_length=200),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_name',
            field=models.CharField(default='Unnamed Party', max_length=140, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-_]+$', 'This field can have characters: alphanumeric, dash, underscore.')]),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_title',
            field=models.CharField(default='Unnamed Track', max_length=200),
        ),
    ]
