# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0004_party_host_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='user_nickname',
            new_name='creator',
        ),
    ]
