# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 18:08
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0004_auto_20160720_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 20, 18, 8, 19, 895998, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_name',
            field=models.CharField(default='', max_length=140, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-_]+$', 'Permitted characters: alphanumeric, dash, underscore.')]),
        ),
        migrations.AlterField(
            model_name='party',
            name='user_nickname',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', 'Permitted characters: alphabet.')]),
        ),
    ]
