# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0004_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='voters',
        ),
        migrations.AddField(
            model_name='voter',
            name='down_tracks',
            field=models.ManyToManyField(related_name='downvoted', to='upnext.Track'),
        ),
        migrations.AddField(
            model_name='voter',
            name='up_tracks',
            field=models.ManyToManyField(related_name='upvoted', to='upnext.Track'),
        ),
    ]
