# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0005_auto_20160726_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
