# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 18:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0005_auto_20160729_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='min_score',
            field=models.IntegerField(default=-10, validators=[django.core.validators.MaxValueValidator(0)]),
        ),
    ]
