# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0006_auto_20160720_1535'),
        ('upnext', '0006_auto_20160720_1536'),
    ]

    operations = [
    ]
