# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 17:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0006_party_min_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='min_score',
            field=models.IntegerField(default=-10, validators=[django.core.validators.MaxValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='track',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
