# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 22:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0007_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 20, 22, 48, 2, 55357, tzinfo=utc)),
        ),
    ]
