# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0007_auto_20160802_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
