# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0008_track_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='username',
            new_name='added_by',
        ),
    ]
