# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0008_auto_20160720_1548'),
        ('upnext', '0007_auto_20160720_1549'),
    ]

    operations = [
    ]
