# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0009_auto_20160803_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='preview',
            field=models.CharField(default='', max_length=200),
        ),
    ]
