# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 18:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0014_auto_20160721_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='uri',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='party',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 22, 18, 30, 48, 939409, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='track',
            name='uri',
            field=models.CharField(default='', max_length=200),
        ),
    ]
