# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 02:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0016_auto_20160722_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 23, 2, 53, 3, 661789, tzinfo=utc)),
        ),
    ]
