# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 05:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0017_auto_20160722_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='uri',
        ),
        migrations.AlterField(
            model_name='party',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 23, 5, 53, 20, 851105, tzinfo=utc)),
        ),
    ]
