# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 06:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0017_auto_20160722_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='uri',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='party',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 23, 6, 2, 10, 359524, tzinfo=utc)),
        ),
    ]
