# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upnext', '0021_auto_20160722_2036'),
        ('upnext', '0018_auto_20160722_2035'),
    ]

    operations = [
    ]
